# Generated by Django 3.2.4 on 2021-07-15 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=12)),
                ('message', models.TextField()),
                ('date', models.DateField(blank=True, default=datetime.datetime(1111, 11, 11, 0, 0), null=True)),
            ],
        ),
    ]
