# Generated by Django 3.2.4 on 2021-07-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='datetime',
        ),
    ]
