# Generated by Django 3.2.4 on 2021-07-17 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_rename_date_contact_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Date_time',
            field=models.DateField(blank=True, default=datetime.datetime(1111, 11, 11, 0, 0), null=True),
        ),
    ]
