# Generated by Django 3.2.4 on 2021-10-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0006_rename_date_time_course_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
