# Generated by Django 3.2.4 on 2021-09-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_rename_c_id_question_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number_of_question',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='passing_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_marks',
            field=models.IntegerField(),
        ),
    ]
