# Generated by Django 3.2.4 on 2021-09-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20210909_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=12)),
                ('message', models.TextField()),
            ],
        ),
    ]
