# Generated by Django 3.2.4 on 2021-10-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3')], max_length=200),
        ),
    ]
