# Generated by Django 3.2.4 on 2021-07-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_signup_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
        migrations.AlterField(
            model_name='signup',
            name='profile_photo',
            field=models.ImageField(upload_to='profile_pic'),
        ),
    ]
